"""
ZeptoMail integration for sending daily reports
Uses ZeptoMail REST API to send transactional emails
"""
import os
import httpx
from typing import Dict, List
from datetime import datetime

ZEPTOMAIL_API_URL = os.getenv("ZEPTOMAIL_API_URL", "https://api.zeptomail.com/v1.1/email")
ZEPTOMAIL_SEND_MAIL_TOKEN = os.getenv("ZEPTOMAIL_SEND_MAIL_TOKEN", "")
ZEPTOMAIL_FROM_ADDRESS = os.getenv("ZEPTOMAIL_FROM_ADDRESS", "")
ZEPTOMAIL_FROM_NAME = os.getenv("ZEPTOMAIL_FROM_NAME", "Pulse AI Agent")
ZEPTOMAIL_TO_ADDRESS = os.getenv("ZEPTOMAIL_TO_ADDRESS", "")


async def send_email_via_zepto(subject: str, html_body: str, text_body: str) -> Dict:
    """
    Helper function to send email using ZeptoMail API
    """
    if not ZEPTOMAIL_SEND_MAIL_TOKEN:
        return {
            "success": False,
            "message": "ZeptoMail token not configured",
            "email_sent": False
        }

    headers = {
        "Accept": "application/json",
        "Content-Type": "application/json",
        "Authorization": f"Zoho-enczapikey {ZEPTOMAIL_SEND_MAIL_TOKEN}"
    }

    payload = {
        "from": {
            "address": ZEPTOMAIL_FROM_ADDRESS,
            "name": ZEPTOMAIL_FROM_NAME
        },
        "to": [
            {
                "email_address": {
                    "address": ZEPTOMAIL_TO_ADDRESS,
                    "name": "User"
                }
            }
        ],
        "subject": subject,
        "htmlbody": html_body,
        "textbody": text_body,
    }

    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            response = await client.post(ZEPTOMAIL_API_URL, json=payload, headers=headers)
            
            if response.status_code in [200, 201]:
                return {
                    "success": True,
                    "message": f"Email sent successfully via ZeptoMail to {ZEPTOMAIL_TO_ADDRESS}",
                    "email_sent": True,
                    "details": response.json()
                }
            else:
                return {
                    "success": False,
                    "message": f"ZeptoMail API error: {response.text}",
                    "email_sent": False
                }
    except Exception as e:
        print(f"Error sending email via ZeptoMail: {e}")
        return {
            "success": False,
            "message": f"Email sending failed: {str(e)}",
            "email_sent": False
        }


async def send_daily_report_email(summaries: list) -> Dict:
    """
    Send daily report via ZeptoMail
    
    Args:
        summaries: List of AI news summaries
        
    Returns:
        Dict with success status and message
    """
    date_str = datetime.utcnow().strftime('%B %d, %Y')
    subject = f"Daily AI Brief - {date_str}"
    
    # Build HTML content
    highlights_html = ""
    highlights_text = ""
    
    for i, s in enumerate(summaries[:15], 1):
        title = s.get('title', 'Untitled')
        summary = s.get('three_sentence_summary', '')
        tags = ', '.join(s.get('tags', []))
        
        # HTML
        highlights_html += f"""
        <div style="margin-bottom: 20px; padding-bottom: 20px; border-bottom: 1px solid #eee;">
            <h3 style="margin-top: 0; color: #333;">{i}. {title}</h3>
            <p style="color: #555; line-height: 1.5;">{summary}</p>
            <p style="color: #888; font-size: 12px;"><strong>Tags:</strong> {tags}</p>
        </div>
        """
        
        # Text
        highlights_text += f"{i}. {title}\n{summary}\nTags: {tags}\n\n"

    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <h1 style="color: #2563eb;">Daily AI Brief</h1>
        <p style="color: #666;">{date_str}</p>
        <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
        <p>Good morning! Here is your daily digest of {len(summaries)} AI/ML news items.</p>
        
        {highlights_html}
        
        <div style="margin-top: 30px; padding-top: 20px; border-top: 2px solid #f0f0f0; text-align: center; color: #888; font-size: 12px;">
            <p>Generated by Pulse AI Agent</p>
        </div>
    </body>
    </html>
    """
    
    text_body = f"""
    Daily AI Brief - {date_str}
    
    Good morning! Here is your daily digest of {len(summaries)} AI/ML news items.
    
    {highlights_text}
    
    Generated by Pulse AI Agent
    """
    
    return await send_email_via_zepto(subject, html_body, text_body)


async def send_test_email() -> Dict:
    """Send a test email to verify ZeptoMail configuration"""
    subject = "Pulse AI Agent - Test Email"
    html_body = "<h1>Test Email</h1><p>This is a test email from your Pulse AI Agent via ZeptoMail.</p>"
    text_body = "Test Email\nThis is a test email from your Pulse AI Agent via ZeptoMail."
    
    return await send_email_via_zepto(subject, html_body, text_body)
