"""
Task scheduler for automated daily and weekly runs
Uses simple time-based scheduling
"""
import asyncio
import schedule
import time
from datetime import datetime, timedelta
from typing import Optional
from sqlalchemy.orm import Session

from agent import run_agent
from db import get_db, save_daily_report, save_weekly_report, get_summaries_by_date, SessionLocal
from summaries import batch_summarize


async def daily_task():
    """
    Daily task: Scrape, process, summarize, and post to X
    Runs every day at a scheduled time
    """
    print(f"\n{'='*60}")
    print(f"⏰ DAILY TASK TRIGGERED - {datetime.utcnow().isoformat()}")
    print(f"{'='*60}\n")
    
    try:
        # Run the agent with X publishing enabled
        final_state = await run_agent(
            publish_to_x=True,
            publish_to_medium=False
        )
        
        # Save daily report to database
        db = SessionLocal()
        try:
            summaries = final_state.get("summaries", [])
            
            if summaries:
                # Create daily report content
                report_content = generate_daily_report_content(summaries)
                
                report_data = {
                    "date": datetime.utcnow(),
                    "title": f"Daily AI Brief - {datetime.utcnow().strftime('%Y-%m-%d')}",
                    "content": report_content,
                    "summaries_included": [s.get("id") for s in summaries if s.get("id")],
                    "sent": False  # Email sending would be implemented separately
                }
                
                save_daily_report(db, report_data)
                print(f"✅ Daily report saved to database")
        finally:
            db.close()
        
        print(f"\n{'='*60}")
        print(f"✅ DAILY TASK COMPLETED")
        print(f"{'='*60}\n")
        
    except Exception as e:
        print(f"❌ Error in daily task: {e}")


async def weekly_task():
    """
    Weekly task: Generate deep dive report and post to Medium
    Runs every week at a scheduled time
    """
    print(f"\n{'='*60}")
    print(f"⏰ WEEKLY TASK TRIGGERED - {datetime.utcnow().isoformat()}")
    print(f"{'='*60}\n")
    
    try:
        # Run the agent with Medium publishing enabled
        final_state = await run_agent(
            publish_to_x=False,
            publish_to_medium=True
        )
        
        # Save weekly report to database
        db = SessionLocal()
        try:
            weekly_report = final_state.get("weekly_report", {})
            
            if weekly_report:
                week_start = datetime.utcnow() - timedelta(days=7)
                week_end = datetime.utcnow()
                
                report_data = {
                    "week_start": week_start,
                    "week_end": week_end,
                    "title": weekly_report.get("title", "Weekly AI Deep Dive"),
                    "content": weekly_report.get("content", ""),
                    "medium_draft_url": weekly_report.get("post_url"),
                    "published": weekly_report.get("success", False)
                }
                
                save_weekly_report(db, report_data)
                print(f"✅ Weekly report saved to database")
        finally:
            db.close()
        
        print(f"\n{'='*60}")
        print(f"✅ WEEKLY TASK COMPLETED")
        print(f"{'='*60}\n")
        
    except Exception as e:
        print(f"❌ Error in weekly task: {e}")


def generate_daily_report_content(summaries: list) -> str:
    """
    Generate daily email report content
    
    Args:
        summaries: List of summaries for the day
        
    Returns:
        HTML/Text content for email
    """
    date_str = datetime.utcnow().strftime('%B %d, %Y')
    
    content = f"""
# Daily AI Brief - {date_str}

Good morning! Here's your daily digest of AI/ML news and developments.

## Today's Highlights ({len(summaries)} items)

"""
    
    for i, summary in enumerate(summaries, 1):
        content += f"""
### {i}. {summary.get('title', 'Untitled')}

{summary.get('three_sentence_summary', '')}

**Tags:** {', '.join(summary.get('tags', []))}
**Novelty Score:** {summary.get('novelty_score', 'N/A')}

---
"""
    
    content += f"""

## Stay Updated

This brief was generated by Pulse, your autonomous AI news intelligence agent.

Happy learning! 🚀

---
*Sent on {date_str}*
"""
    
    return content


def schedule_tasks():
    """
    Schedule daily and weekly tasks
    """
    # Schedule daily task at 9:00 AM UTC
    schedule.every().day.at("09:00").do(lambda: asyncio.create_task(daily_task()))
    
    # Schedule weekly task every Monday at 10:00 AM UTC
    schedule.every().monday.at("10:00").do(lambda: asyncio.create_task(weekly_task()))
    
    print("📅 Tasks scheduled:")
    print("   • Daily: Every day at 09:00 UTC")
    print("   • Weekly: Every Monday at 10:00 UTC")


async def run_scheduler():
    """
    Run the task scheduler
    """
    print("\n" + "="*60)
    print("🕐 PULSE SCHEDULER STARTED")
    print("="*60 + "\n")
    
    schedule_tasks()
    
    while True:
        schedule.run_pending()
        await asyncio.sleep(60)  # Check every minute


if __name__ == "__main__":
    # For testing, run daily task immediately
    asyncio.run(daily_task())
